### ISSUE TITLE
UniswapV3PoolDeployer.deploy factory parameter is always address(this).

### ISSUE THREAD

**Issue by wjmelements** [Uniswap/uniswap-v3-core#442]
The redundant `factory` parameter in `deploy` should be removed to save gas. `address(this)` is 2 gas, while the parameter will be DUP'd and eventually POP'd.

**Comment by moodysalem** [comment]
In the tests, we do not use `address(this)`

https://github.com/Uniswap/uniswap-v3-core/blob/main/contracts/test/MockTimeUniswapV3PoolDeployer.sol

**Comment by wjmelements** [comment]
So, you need better tests

**Comment by wjmelements** [comment]
You can remove `factory` from parameters altogether, saving at least `25000` gas, by using `msg.sender`.

**Comment by moodysalem** [comment]
> You can remove `factory` from parameters altogether, saving at least `25000` gas, by using `msg.sender`.

The expected difference in gas cost is an order of magnitude less than `25000`, because the SSTORE is cleared after the deploy. The only expected cost is the 1600 for the SSTORE + clear, and some extra calldata, which is insignificant relative to the 4.5M gas cost to deploy a pair.

**Comment by wjmelements** [comment]
> > You can remove `factory` from parameters altogether, saving at least `25000` gas, by using `msg.sender`.
> 
> The expected difference in gas cost is an order of magnitude less than `25000`, because the SSTORE is cleared after the deploy. The only expected cost is the 1600 for the SSTORE + clear, and some extra calldata, which is insignificant relative to the 4.5M gas cost to deploy a pair.

I measure 4157 in Istanbul but it will be higher in Berlin and the refund may go away in London. But you shouldn't talk about relative costs; 4000 gas is 4000 gas, no matter the total.
