### ISSUE TITLE
Improve the 'divRoundingUp' function in the 'UnsafeMath' Library

### ISSUE THREAD

**Issue by barakman** [Uniswap/uniswap-v3-core#445]
In the [UnsafeMath Library](https://github.com/Uniswap/uniswap-v3-core/blob/main/contracts/libraries/UnsafeMath.sol#L14), you can improve this:
```
z = (x / y) + (x % y > 0 ? 1 : 0);
```
Which consists of 1 div, 1 add, 1 mod, 1 jump, 4 loads and 1 store.

To this:
```
z = x > 0 ? (x - 1) / y + 1 : 0;
```
Which consists of 1 div, 1 add, 1 sub, 1 jump, 3 loads and 1 store.

Even if we ignore the improvement of 3 vs 4 loads (say, the compiler can opt it out), we still replace the 'mod' operation (5 gas) with a 'sub' operation (3 gas).

A minor diff in the behavior: `divRoundingUp(0, 0)` will return 0 instead of panicking (divide by zero).

If this is critical, then you can slightly modify the suggested expression into:
```
z = x > 0 ? (x - 1) / y + 1 : x / y;
```
Which for `x == 0` will yield the same number of loads (3), alongside 1 div, 1 jump and 1 store (still better than your current implementation, which costs the same for both sides of the 'greaterThan' condition).

**Comment by barakman** [comment]
Needless to mention, `(x - 1) / y + 1` can never overflow or underflow when `x > 0`.

**Comment by moodysalem** [comment]
I believe it can also panic if `y = type(uint256).max`

**Comment by moodysalem** [comment]
Sent a PR, gas savings are very minor (0.05% on a swap) so unlikely to merge, even though it seems very low risk

**Comment by barakman** [comment]
> ~I believe it can also panic if `y = type(uint256).max`~
> 
> Nevermind, I believe the intended order of operations is the division followed by the addition of 1

For your first (now deleted) comment - panic would only occur when asserting, dividing by zero, passing an illegal enum value or accessing an array at an illegal index.
Dividing by max-uint256 won't trigger panic (and there's no reason for us to require this behavior either).

For your second comment - I don't quite understand what you mean.
Of course the intended order of operations in `(x - 1) / y + 1` is the division followed by the addition of 1.
What else would it be?

**Comment by moodysalem** [comment]
> For your second comment - I don't quite understand what you mean.
> Of course the intended order of operations in `(x - 1) / y + 1` is the division followed by the addition of 1.
> What else would it be?

My first comment was me misunderstanding it to be `(x - 1) / (y + 1)`.

**Comment by barakman** [comment]
Gotcha

**Comment by barakman** [comment]
> Sent a PR, gas savings are very minor (0.05% on a swap) so unlikely to merge, even though it seems very low risk

Your optimization for calling function `balanceOf` ([here](https://github.com/Uniswap/uniswap-v3-core/blob/main/contracts/UniswapV3Pool.sol#L141-L159) saves 151 gas per call according to my empiric test (using `gasleft()` inside a small helper function). Pretty sure that's less than 0.05% per any flow where those optimized functions of yours are used, while they look potentially of a much higher risk factor.

**Comment by moodysalem** [comment]
> Actually, it was 151 out of around 4450 (can't remember the exact figure), which is a little over 3%, so perhaps it's worth the risk.

The gas savings of that change are here (no empiric test needed):
https://github.com/Uniswap/uniswap-v3-core/pull/437/files#diff-9dd2638a0155da6d7dcf09f3866954da30e66e6a3569a6aa7794604e51ad030c

367 per swap, up to 751 for mints. 

We also had a lot of review, discussion, testing of the change to make sure it was equivalent.

**Comment by moodysalem** [comment]
This is actually mentioned in the ABDK audit
https://github.com/Uniswap/uniswap-v3-core/blob/main/audits/abdk/audit.pdf
Point 3.66

With efficient assembly version:
```
z := add (div (x, y), gt (mod (x, y), 0))
```

**Comment by barakman** [comment]
@moodysalem:
That's just an assembly implementation of the original statement.
It would still result in 1 div, 1 add, 1 mod, 1 jump, 4 loads and 1 store.
My suggestion (which can also be translated to assembly for all it matters) slightly reduces this const.

See my analysis of both options at the top of this thread.

**Comment by moodysalem** [comment]
> It would still result in 1 div, 1 add, 1 mod, 1 jump, 4 loads and 1 store.

There is no jump here, because there is no branching.
It turns out this is cheaper than the option you suggested (see gas snapshots):
https://github.com/Uniswap/uniswap-v3-core/pull/446/commits/68c9e2a5f91c25b19a8ef42c2ff26a4454e04c60#diff-9dd2638a0155da6d7dcf09f3866954da30e66e6a3569a6aa7794604e51ad030c

**Comment by barakman** [comment]
Then there is no jump in my suggestion either (you can replace the 'jump' that i wrote in both cases with 'gt').
In order to conduct a proper gas comparison, i believe that you should also translate my suggestion to assembly (i.e., compare assembly vs assembly).

**Comment by moodysalem** [comment]
> i believe that you should also translate my suggestion to assembly

I'm not sure how to translate your suggestion to not have the jump, and it's probably only a difference of a single mod opcode. 

I think the reason the no-jump assembly version is so much cheaper is it's probably getting inlined into the calling function.
https://blog.soliditylang.org/2021/03/02/saving-gas-with-simple-inliner/

**Comment by kristinelin** [comment]
> > ~I believe it can also panic if `y = type(uint256).max`~
> > Nevermind, I believe the intended order of operations is the division followed by the addition of 1
> 
> For your first (now deleted) comment - panic would only occur when asserting, dividing by zero, passing an illegal enum value or accessing an array at an illegal index. Dividing by max-uint256 won't trigger panic (and there's no reason for us to require this behavior either).
> 
> For your second comment - I don't quite understand what you mean. Of course the intended order of operations in `(x - 1) / y + 1` is the division followed by the addition of 1. What else would it be?
