### ISSUE TITLE
Redundant slot0.unlock in `swap`

### ISSUE THREAD

**Issue by brockelmore** [Uniswap/uniswap-v3-core#448]
The `swap` function has the `lock` modifier but explicitly resets the lock [here](https://github.com/Uniswap/uniswap-v3-core/blob/83ddb278c6323b908d61d4c8e891ff842efac9b9/contracts/UniswapV3Pool.sol#L686).

Is this intentional? Without the optimizer enabled, this would seem to incur a 1500 gas extra gas cost (from a quick test). With it enabled to the 800 runs as defined by hardhat config, the difference goes away. Removing it does seemingly save about 7 bytes per deployment, which is about 1400 gas per pool deployment (in a simple test deployment that explores explicitly whether to have that line or not). I haven't tested with the full contract.

Here is the sample code:
```
contract T {
    modifier lock() {
        slot0.unlocked = false;
        _;
        slot0.unlocked = true;
    }
    
    struct Slot0 {
        bool unlocked;
    }
    
    Slot0 slot0;
    
    constructor() public {
        slot0.unlocked = true;
    }
    function t() public lock returns (int256, int256) {
        slot0.unlocked = true;
        return (0, 0);
    }
    
    
}

contract T2 {
    modifier lock() {
        slot0.unlocked = false;
        _;
        slot0.unlocked = true;
    }
    
    struct Slot0 {
        bool unlocked;
    }
    
    Slot0 slot0;
    
    constructor() public {
        slot0.unlocked = true;
    }
    
    function t() public lock returns (int256, int256) {
        return (0, 0);
    }
}
```

**Comment by moodysalem** [comment]
> The swap function has the lock modifier

The swap function does not have the lock modifier https://github.com/Uniswap/uniswap-v3-core/blob/83ddb278c6323b908d61d4c8e891ff842efac9b9/contracts/UniswapV3Pool.sol#L512-L518

**Comment by brockelmore** [comment]
Sorry! :(

**Comment by brockelmore** [comment]
[This line](https://github.com/Uniswap/uniswap-v3-core/blob/99223f33fd69a9e024f00bd8eea17b029d3f8f2d/contracts/UniswapV3Pool.sol#L107) lead me to believe that swap would have had the reentrancy lock, so I failed to check the actual function. Maybe remove swap from this documentation?
