### ISSUE TITLE
Why is `optimize-runs` parameter set to 800?

### ISSUE THREAD

**Issue by hrkrshnn** [Uniswap/uniswap-v3-core#457]
In https://github.com/Uniswap/uniswap-v3-core/blob/main/hardhat.config.ts#L16, the [runs parameter](https://docs.soliditylang.org/en/v0.8.3/using-the-compiler.html?highlight=optimize-runs#optimizer-options) is set to 800. Which means that functions in the contract is expected to only run around 800 times.

I was wondering if it's because increasing lead to hitting bytecode size limit or perhaps the bytecode doesn't change after increasing the value?

Just reaching out since, solidity team thinks that `runs` parameter may have a misleading name, and we were considering renaming it: see https://github.com/ethereum/solidity/issues/11084

**Comment by moodysalem** [comment]
> I was wondering if it's because increasing lead to hitting bytecode size limit or perhaps the bytecode doesn't change after increasing the value?

Yes this is why we didn't set it higher. 

We also ran a query and found Uniswap v2 pairs received around ~2k calls per pair on average, and since there are potentially 3x as many v3 pairs, 800 isn't too far from the actual number of runs.

**Comment by moodysalem** [comment]
Our factory bytecode size is also snapshotted here
https://github.com/Uniswap/uniswap-v3-core/blob/f03155670ec1667406b83a539e23dcccf32a03bc/test/__snapshots__/UniswapV3Factory.spec.ts.snap#L5

**Comment by axic** [comment]
@moodysalem thanks for the quick answer, that is interesting!

Do you have an idea which parts of the contracts use the most gas/bytecode size?

**Comment by moodysalem** [comment]
> @moodysalem thanks for the quick answer, that is interesting!
> 
> Do you have an idea which parts of the contracts use the most gas/bytecode size?

We made some sacrifices just to make the contract fit, e.g. removing revert reasons which seems to cost about 50 bytes per revert reason (vs. a single character revert reason) https://github.com/Uniswap/uniswap-v3-core/pull/355
