### ISSUE TITLE
Hardcoded gas in tests, Hardhat and Berlin

### ISSUE THREAD

**Issue by fvictorio** [Uniswap/uniswap-v3-core#473]
Hi, we just published `hadhat@2.2.0`, which upgrades the VM and adds support for Berlin. Before releasing it, we ran our tests in several popular projects that use Hardhat to make sure that everything works fine.

When we did that in Uniswaps' repo, we noticed that a lot of tests fail now because they check that the used gas matches some given value. So this is just a friendly warning that that will happen when you upgrade. If you want to temporarily keep the previous behavior, you just need to do this in your config:

```javascript
networks: {
  hardhat: {
    hardfork: "muirGlacier"
  }
}
```

**Comment by moodysalem** [comment]
The snapshots can be updated by running `yarn test` with the environment variable `UPDATE_SNAPSHOTS` set to 1

e.g.
`UPDATE_SNAPSHOTS=1 yarn test`

**Comment by fvictorio** [comment]
Oh, didn't know that :sweat_smile: That's so cool!

I'll close this issue since it was just to let you folks know about this change.

**Comment by moodysalem** [comment]
I tried updating hardhat and adding the key to the config and running the tests but it didn't fail for me, can you send a PR with the changes?

**Comment by moodysalem** [comment]
Seems like it's actually the default! Removing the hardfork key made it work. Maybe a bug in hardhat?
https://github.com/Uniswap/uniswap-v3-core/pull/475/files#diff-4273833f16d0d3b3e1f4e5504d7cd034c39f077dcd93a6ca16503ad9f489f696R42

Any idea why the gas tests would be cheaper for a lot of important operations?!

**Comment by fvictorio** [comment]
> Seems like it's actually the default!

Yes, "berlin" is the default value in the latest release, and that triggers the gas changes.

> Any idea why the gas tests would be cheaper for a lot of important operations?!

I think this is expected. For example, an SSLOAD followed by an SSTORE to the same key will be cheaper in Berlin. I wrote more about that [here](https://hackmd.io/@fvictorio/gas-costs-after-berlin) if you are interested.
