### ISSUE TITLE
Swap problem

### ISSUE THREAD

**Issue by Pauchuk** [Uniswap/uniswap-v3-core#477]
Hello. Hope this reaches you :)
So, I made Binance Smart Chain on Metamask and connected Uniswap with MM to exchange ETH to my desired token.
And why would Uniswap app even allow me to choose BNB to my desired token swap pop up. That option should not be even showed, even on ETH mainnet, that confuses a lot people.

![image](https://user-images.githubusercontent.com/82718713/115118484-027efc80-9fac-11eb-8a34-bfbff8be5e3f.png)

**Comment by Pauchuk** [comment]
We want this environment to be friendly for everyone, but these things just retracts, prevents "average" user to even start diving in to crypto world :)

**Comment by moodysalem** [comment]
I do not understand your comment, and wrong venue anyway. Please use the Discord.
