### ISSUE TITLE
Only 800 runs?

### ISSUE THREAD

**Issue by wjmelements** [Uniswap/uniswap-v3-core#485]
Runs are the number of times the code will be run, and it will likely be more than 800. UniswapV2 uses 999999. I don't use hardhat but I see some 800-run deployments on testnets so I want to make sure V3 will be deployed with more than 800 runs.

**Comment by moodysalem** [comment]
We are at the bytecode size limit: https://github.com/Uniswap/uniswap-v3-core/blob/main/test/__snapshots__/UniswapV3Factory.spec.ts.snap#L5
