### ISSUE TITLE
Remove recipient/to field and use msg.sender instead

### ISSUE THREAD

**Issue by Zergity** [Uniswap/uniswap-v3-core#487]
In short: what is the reason behind the `recipient` design instead of just `msg.sender`?

From v2, the `to` (`recipient`) field seems odd in the smart-contract context. It detaches the output token ownership from the input token ownership. I'm not sure what the reason behind this design, but it causes some troubles in developing 3rd party contract.

I'm developing a decentralized bank, where user deposit their tokens and some *delegates* will execute farming operations (`swap`, `addLiquidity`, `removeLiquidity`, etc.) on behalf of the bank. The key decentralization here is that no *delegate* can withdraw any token, they can only tell the bank contract to interact with trusted pool/routers. If the protocol/periphery contracts mint/swap to `msg.sender`, the ownership of each token is kept intact. With `recipient` field as current design, extra operation has to be caried out for ownership verification.

**Comment by moodysalem** [comment]
Your comment does not make sense. Just set recipient to `address(this)` in your smart contract.

**Comment by Zergity** [comment]
> Your comment does not make sense. Just set recipient to `address(this)` in your smart contract.

Not when you allow abittrary function call using low level `addess.call(input)`.

The point is to keep the token ownership with abstract the function call, not manually hardcode every single call. There more more contract interfaces to interact with other than Uniswap.

**Comment by moodysalem** [comment]
> > Your comment does not make sense. Just set recipient to `address(this)` in your smart contract.
> 
> 
> 
> Not when you allow abittrary function call using low level `addess.call(input)`.
> 
> 
> 
> The point is to keep the token ownership with abstract function calls, not manually hardcode every single call. There're more contract interfaces to interact with other than Uniswap.

This is an issue with your design, not the flexibility of the periphery. There are many trivial workarounds (eg create a separate contract that calls the router)
