### ISSUE TITLE
Verify contracts on optimistic etherscan

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/uniswap-v3-core#493]
Moody is working on it. Potentially blocked on etherscan.

**Comment by moodysalem** [comment]
i'm not working on it

my last message to the chat was

> throws when trying to verify the tickmath library, doesn’t know about optimism’s etherscan endpoints
$ /Users/moody/IdeaProjects/uniswap/v3/optimism/core/node_modules/.bin/hardhat verify --network optimism 0x308C3E60585Ad4EAb5b7677BE0566FeaD4cb4746
Error in plugin @nomiclabs/hardhat-etherscan: An etherscan endpoint could not be found for this network. ChainID: 10. The selected network is optimism.
> Possible causes are:
>  - The selected network (optimism) is wrong.
>  - Faulty hardhat network config.

would be best for optimism to address this with a pull request to the plugin. we verified all contracts on other networks using the plugin, and it's very laborious to do it by hand in the etherscan interface

**Comment by willhennessy** [comment]
messaged optimism to please submit a PR to the hardhat-etherscan repo

**Comment by moodysalem** [comment]
with hardhat-etherscan 2.1.4, this is the latest error (tickmath again)

```
$ /Users/moody/IdeaProjects/uniswap/v3/optimism/core/node_modules/.bin/hardhat verify --network optimism 0x308C3E60585Ad4EAb5b7677BE0566FeaD4cb4746
Error in plugin @nomiclabs/hardhat-etherscan: The contract you want to verify was compiled with solidity <0.4.7, but your configured compiler version is: 0.7.6.

Possible causes are:
  - You are not in the same commit that was used to deploy the contract.
  - Wrong compiler version selected in hardhat config.
  - The given address is wrong.
  - The selected network (optimism) is wrong.
```

**Comment by willhennessy** [comment]
Etherscan was supposed to merge functionality over the weekend. Then Matt will do stuff. Noah will follow up!

**Comment by willhennessy** [comment]
update from matt solomon:

So all non-pool contracts should now verified on mainnet

I verified the ETH/DAI mainnet pool, but this did not carry over to automatically verify other pools due to the use of immutables. They pushed a fix for this to L1 Etherscan a few weeks back and plan to add it to Optimistic Etherscan soon
